set nocompatible " be iMproved, required
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" files explorer (NERDTree)
Plugin 'scrooloose/nerdtree'

" nice color scheme
Plugin 'AlexeySachkov/wombat256.vim'

" status bar
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'mileszs/ack.vim'

" Git integrations
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'

" vim-notes
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-notes'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" At least let yourself know what mode you're in
set showmode

colorscheme wombat256mod

set scrolljump=7
set scrolloff=7

set expandtab
set smarttab
set smartindent
set softtabstop=2
set shiftwidth=2
set tabstop=4

set ruler
set number
set cursorline
set wrap

" FIXME: cursorline doesn't work in the area which colored by colorcolumn
let &colorcolumn=join(range(81,999),",")

set hlsearch
set incsearch
set ignorecase
set smartcase

set splitbelow
set splitright

nnoremap <Tab> <C-W><C-W>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

:nnoremap <silent> <F9> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

:set list
:set listchars=tab:»~,trail:·

syntax on

" TODO: let's use FZF and buffers

" TODO: look at other note plugins, maybe there are something better?
" vim-notes plugin settings
:let g:notes_suffix = '.md'
:let g:notes_directories = ['~/vim-notes']

" vim-airline plugin settings
:let g:airline#extensions#tabline#enabled = 1
" I don't use buffers and this feature slows vim with many buffers opened
:let g:airline#extensions#tabline#show_buffers = 0
" TODO: remove branch name from status bar
" TODO: update current position section: remove all except curline/numoflines : column
" TODO: switch to lightline? What about tabs color?

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" clang-format integration
map <F7> :py3f ~/clang-format-py3.py

augroup filetypedetect
  au BufRead,BufNewFile *.cl set filetype=c
  " associate *.cl with c filetype
augroup END

let s:vimrc_dir = expand('<sfile>:p:h')
let s:vimrc_additional_configs = [
\ 'toggles.vim'
\ ]

for config_file in s:vimrc_additional_configs
  execute('source ' . s:vimrc_dir . '/.dotfiles/vim/' . config_file)
endfor
