set nocompatible " be iMproved, required

" At least let yourself know what mode you're in
set showmode

colorscheme desert

set scrolljump=7
set scrolloff=7

set expandtab
set smarttab
set smartindent
set softtabstop=2
set shiftwidth=2
set tabstop=4

set ruler
set number
set colorcolumn=80
set cursorline
set wrap

set hlsearch
set incsearch
set ignorecase
set smartcase

set splitbelow
set splitright

nnoremap <Tab> <C-W><C-W>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

:nnoremap <silent> <F9> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>
:map <F2> :NERDTreeToggle<CR>

:set list
:set listchars=tab:»~,trail:·

syntax on
filetype plugin indent on

" phpqa plugin settings
:let g:phpqa_messdetector_autorun = 0
:let g:phpqa_codesniffer_autorun = 0

" vim-notes plugin settings
:let g:notes_suffix = '.md'

execute pathogen#infect()
